version: "3"

services:
  web:
    build: ./docker/web/
    ports:
        - "80:80"
    volumes:
        - ".:/var/www/html:rw"
    networks:
        -  db
    depends_on:
        -  db

  db:
    image: mongo:3.4
    volumes:
        - data-volume:/data/db
    ports:
        - 27017:27017
    restart: always
    networks:
        - db

volumes:
  data-volume:

networks:
  db:
